### ISSUE TITLE
Deployment scripts improvement 

### ISSUE THREAD

**Issue by b00ris** [corestario/tendermint_fork#3]
We need:
* ability to chose a number of nodes
* ability to chose a number of data centres
* ability to deploy different networks

related to https://github.com/dgamingfoundation/dcr-cosmos/issues/5
related to https://github.com/dgamingfoundation/tendermint/issues/2

**Comment by b00ris** [comment]
Prepared PR in branch https://github.com/dgamingfoundation/tendermint/tree/2-dg-deploy

**Comment by vshvsh** [comment]
Good enough for benchmarks 1-3 form #6 and hooking up grafana

**Comment by b00ris** [comment]
Grafana issue could be also closed http://142.93.247.189:3000/d/BLp0Pvwik/tendermint?orgId=1&from=1547586064817&to=1547586196245
